// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sftpconnection.proxies;

public enum AuthenticationType
{
	Username_and_password(new java.lang.String[][] { new java.lang.String[] { "en_US", "Username and password" } }),
	Username_and_connection_specific_private_key(new java.lang.String[][] { new java.lang.String[] { "en_US", "Username and connection specific private key" } }),
	Username_and_general_private_key(new java.lang.String[][] { new java.lang.String[] { "en_US", "Username and general private key" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private AuthenticationType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
